import React from "react";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "../globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {

    return (
        <ClerkProvider appearance={{
            baseTheme: dark,
        }}>
        <html lang='en'>
            <body className={`${montserrat.className} bg-dark-1`}>{children}</body>
        </html>
        </ClerkProvider>
    );
}